### ISSUE TITLE
concurrent chunk encryption/decryption

### ISSUE THREAD

**Issue by gaviezri** [barakg43/UsedTube#9]
the encryptor can maintain a threadpool of 25 workers ( derived from FPS ).
a chunk is equivalent to a frame.
each chunk is independent and will be handled once.
therefore the processing can be divided among the workers.

I thought a list [<size of the precalculated frames>]  could be allocated beforehand;
each worker will receive the chunk and an index/reference that refers to their ordinal position in the file.
a worker will encrypt the chunk into a frame and will put the result in the list based on the given index/reference.
when they are done the list contains the frames in the order that is equivalent to the order of the chunks in the file.
the encryptor waits for all threads to finish;

at first glance it seems there are no critical sections in that implementation.

**Comment by gaviezri** [comment]
- [ ] Encryption Concurrency
- [ ] Decryption Concurrency

**Comment by barakg43** [comment]
gal implement the concurrent for both of them
